### PR TITLE
Add a macro to fetch external data

### PR DESCRIPTION
**Pull request by unlocomqx**
This commit aims to implement a URL macro which may be useful for inserting dynamic data from a web address. 
I aim to use it mainly for getting my external IP address as it changes often
`IP: [[%f(https://api.ipify.org/?format=text)]]`
I hope you find it useful too!

Regarding the implementation itself, since the request should be asynchronous, I set a unique placeholder for each request. This placeholder would be later replaced by the request response.
The code will prevent invoking the callback until all requests in the snippet have completed.

I'll be glad to have your feedback on this

**Edit:**
Changed %u to %f

### CODE REVIEW

**Comment by GaurangTandon** [comment]
Thanks for commit! I understand that this code fetches the dynamic data from an external resource and pastes it _as is_ into the snip body. I wish to discuss a few things though:

1. What kind of formats the data can be? We should support only multiline plain text, right?
2. What size the data could be? Does the size even matter? IMHO it's the user's responsibility to decide if the data could be big enough to take time to be fetched from that resource.
3. There's already a macro with `%u` (#34). I suggest we rename this one to `%f()` - `f` for `f`etch external data.

**Comment by unlocomqx** [comment]
I will change the %u to %f to avoid the conflict.
Regarding the usage, it's meant for (short) plain text or plain html data, like the IP address example or a dynamic signature fetched from a server. 
A more advanced user may create his own web service and use it to return a text/html response but in general the user should be aware that the content will be pasted as is, thus getting a full webpage won't be a good idea.
I wish we get more feedback from other users, is there a forum related to this extension?
Cheers

**Comment by GaurangTandon** [comment]
Perfect. Thanks for the details. I'll try and put this into the very next update.

> I wish we get more feedback from other users, is there a forum related to this extension?

I always thought GitHub is good enough for an easy-to-use-and-manage forum. Is there any reason why you would think otherwise?

**Comment by unlocomqx** [comment]
I think of it more for developers but not as much for regular users, I may have to change my view, right?
I will amend my commit to modify the %u part :)

**Pull request closed without merging**
